var QB={
japanese:{
basic:[
{q:"What does 'arigatou' mean?",o:["Thank you","Goodbye","Good morning","Please"],a:0,f:"Arigatou = Thank you. Arigatou gozaimasu is the formal version."},
{q:"How do you say 'Good morning' in Japanese?",o:["Konnichiwa","Ohayou gozaimasu","Konbanwa","Sayounara"],a:1,f:"Ohayou gozaimasu = Good morning. Konnichiwa = Hello/afternoon. Konbanwa = Good evening."},
{q:"What does 'hai' mean?",o:["No","Maybe","Yes","Please"],a:2,f:"Hai = Yes. Iie = No."},
{q:"Which writing system uses simple curved characters?",o:["Kanji","Romaji","Hiragana","Katakana"],a:2,f:"Hiragana has 46 curved characters for native Japanese words and grammar."},
{q:"What does 'mizu' mean?",o:["Fire","Water","Tree","Earth"],a:1,f:"Mizu = Water. Hi = Fire, Ki = Tree, Tsuchi = Earth."},
{q:"'Ikura desu ka' is used to ask?",o:["Where is it?","What is your name?","How much does it cost?","What time?"],a:2,f:"Ikura desu ka = How much is it? Essential for shopping."},
{q:"What does 'kawaii' mean?",o:["Scary","Cute","Strong","Fast"],a:1,f:"Kawaii = Cute/Adorable. Famous worldwide through Japanese pop culture."},
{q:"What is 'gakkou' in English?",o:["School","Hospital","Station","Shop"],a:0,f:"Gakkou = School. Byouin = Hospital, Eki = Station, Mise = Shop."},
{q:"How do you write 3 in Japanese?",o:["Ichi","Ni","San","Shi"],a:2,f:"San = 3. Ichi = 1, Ni = 2, Shi/Yon = 4."},
{q:"What does 'tabemasu' mean?",o:["I drink","I eat","I sleep","I go"],a:1,f:"Tabemasu = to eat (polite form). Nomimasu = to drink."},
{q:"'Toire wa doko desu ka' means?",o:["What is the time?","Where is the toilet?","How far is it?","Is this seat free?"],a:1,f:"Toire wa doko desu ka = Where is the toilet? Doko = Where."},
{q:"What does 'sumimasen' mean?",o:["Good luck","Excuse me / Sorry","Well done","Come here"],a:1,f:"Sumimasen = Excuse me / I'm sorry. Used to get attention and to apologize."},
{q:"Which color is 'aka' in Japanese?",o:["Blue","Green","White","Red"],a:3,f:"Aka = Red. Ao = Blue, Midori = Green, Shiro = White."},
{q:"'Kyou' means?",o:["Yesterday","Tomorrow","Today","Now"],a:2,f:"Kyou = Today. Kinou = Yesterday. Ashita = Tomorrow."},
{q:"What is 'densha' in English?",o:["Bus","Train","Bicycle","Taxi"],a:1,f:"Densha = Train (electric). Japan has the world's best train system!"},
{q:"What does 'namae' mean?",o:["Age","Job","Name","Address"],a:2,f:"Namae = Name. Watashi no namae wa ___ desu = My name is ___."},
{q:"'Wakarimasen' means?",o:["I don't understand","I don't know","I can't see","I can't hear"],a:0,f:"Wakarimasen = I don't understand. Very useful phrase for beginners!"},
{q:"What does the kanji 山 mean?",o:["River","Forest","Mountain","Ocean"],a:2,f:"Yama = Mountain. Kawa = River, Mori = Forest, Umi = Ocean."},
{q:"'Tomodachi' means?",o:["Family","Teacher","Friend","Neighbour"],a:2,f:"Tomodachi = Friend. Kazoku = Family, Sensei = Teacher."},
{q:"What does 'tenki' mean?",o:["Temperature","Season","Weather","Climate"],a:2,f:"Tenki = Weather. Kyou no tenki wa ii desu ne = Nice weather today!"}
],
intermediate:[
{q:"Which particle marks the topic of a sentence?",o:["Ga","Wo","Ni","Wa"],a:3,f:"Wa is the topic particle marking what the sentence is about. Ga is the subject particle."},
{q:"What is the te-form of taberu?",o:["Tabete","Tabeta","Tabere","Tabeyo"],a:0,f:"Tabete is the te-form. It connects verbs and forms progressive tense."},
{q:"JLPT N4 tests which approximate CEFR level?",o:["A1","A2-B1","B2","C1"],a:1,f:"JLPT N4 is approximately A2-B1. You can handle basic everyday conversations."},
{q:"What does the suffix -tai express?",o:["Must do","Want to do","Should do","Can do"],a:1,f:"-tai expresses desire: tabetai = want to eat."},
{q:"Which kanji means 'person'?",o:["Wood","Person","Fire","Water"],a:1,f:"Jin/Hito = Person. Appears in many compounds like Nihonjin (Japanese person)."},
{q:"What does 'mou' mean with a positive verb?",o:["Not yet","Already","Still","Again"],a:1,f:"Mou + positive = Already (mou tabeta = already ate). Mada = still/not yet."},
{q:"Which counter is used for flat objects?",o:["Hon","Mai","Satsu","Dai"],a:1,f:"Mai counts flat things: 3-mai no kami = 3 sheets of paper."},
{q:"What is the conditional form using -tara?",o:["If/When, then...","Because...","Although...","While doing..."],a:0,f:"-tara = if/when. Ame ga futtara, ie ni iru = If it rains, I'll stay home."},
{q:"Which is a na-adjective?",o:["Ookii","Shizuka","Atarashii","Takai"],a:1,f:"Shizuka (quiet) is a na-adjective. Na-adjectives take na before nouns."},
{q:"What does -te miru express?",o:["Try doing","Finish doing","Continue doing","Stop doing"],a:0,f:"-te miru = try doing to see what happens. Tabete mita = tried eating it."},
{q:"What level of JLPT tests reading a newspaper?",o:["N5","N4","N3","N1"],a:3,f:"JLPT N1 is the highest level. Only about 30% of takers pass."},
{q:"Which particle indicates destination?",o:["De","Ni/E","Kara","Made"],a:1,f:"Ni/E both indicate destination. De marks where an action occurs."},
{q:"What does -nagara mean?",o:["Before doing","After doing","While doing simultaneously","Instead of doing"],a:2,f:"-nagara = while doing simultaneously. Ongaku wo kikinagara benkyou suru."},
{q:"What is keigo?",o:["Slang","Formal/honorific language","Children's language","Regional dialect"],a:1,f:"Keigo = honorific language used with superiors, customers, and strangers."},
{q:"'Motto yukkuri hanashite kudasai' means?",o:["Speak louder","Speak more slowly please","Repeat that","Write it down"],a:1,f:"Motto = more, yukkuri = slowly, hanashite = speak, kudasai = please."}
],
advanced:[
{q:"Which grammar pattern expresses 'even if'?",o:["-temo","-kara","-node","-shi"],a:0,f:"-temo = even if/even though. Ame ga futtemo iku = I'll go even if it rains."},
{q:"The N2 grammar -ni hanshite means?",o:["In accordance with","Contrary to","Because of","For the sake of"],a:1,f:"-ni hanshite = contrary to / against. Yosou ni hanshite = contrary to expectations."},
{q:"What does 'osewa ni natte orimasu' mean?",o:["Thank you for your patronage","I apologize","Please accept this gift","Looking forward to working with you"],a:0,f:"Standard opening of Japanese business emails meaning 'Thank you for your continued support.'"},
{q:"'Iwayuru' modifies a noun to mean?",o:["So-called","Unexpected","Highly regarded","Uncertain"],a:0,f:"Iwayuru = so-called / what is known as. Common in formal writing."},
{q:"What does the suffix -gachi indicate?",o:["Tendency to (often negative)","Ability to","Just finished","About to do"],a:0,f:"-gachi = tendency to (often negative). Chikoku shigachi = tends to be late."},
{q:"What is the passive form of kaku (write)?",o:["Kakareru","Kakaseru","Kakaserareru","Kakeru"],a:0,f:"Kakareru = to be written (passive). Kakaseru = make someone write (causative)."},
{q:"'Hara wo watte hanasu' means?",o:["To eat together","To speak frankly","To argue","To keep a secret"],a:1,f:"Literally 'split the belly and talk'. Means to speak frankly/openly. Business idiom."},
{q:"What is the honorific of taberu for someone else's action?",o:["Tabemasu","Meshiagarimasu","Itadakimasu","Otabeshimasu"],a:1,f:"Meshiagarimasu is the sonkeigo (respectful) form for when a superior eats."},
{q:"'Sashitsukae nakereba' is used before?",o:["An apology","An urgent demand","A polite information request","A command"],a:2,f:"= if it's not inconvenient. Softens questions politely. Very formal business Japanese."},
{q:"'Moushiwake gozaimasen' vs 'sumimasen' differs how?",o:["Same meaning","Moushiwake is much deeper/formal apology","Sumimasen is only for strangers","Moushiwake is only written"],a:1,f:"Moushiwake gozaimasen is a very deep formal apology used in business/serious situations."},
{q:"Which particle combination marks a deadline?",o:["De + location","Wo + movement","Made ni","Kara for reason"],a:2,f:"Made ni = by (a deadline). 5-ji made ni kite kudasai = Please come by 5 o'clock."},
{q:"What does -te ageru express?",o:["Receive a favour","Do something for someone","Be made to do","Want to do"],a:1,f:"-te ageru = do something for someone (you to them, as a favour)."},
{q:"What is 'funin' in business context?",o:["Retirement","Transfer to new post","Promotion","Resignation"],a:1,f:"Funin = being posted/transferred to a new location. Kaigai funin = overseas posting."}
]
},
french:{
basic:[
{q:"What does 'Bonjour' mean?",o:["Goodbye","Good evening","Hello / Good day","Thank you"],a:2,f:"Bonjour = Hello / Good day. Bonsoir = Good evening. Au revoir = Goodbye."},
{q:"'Je m'appelle Marie' means?",o:["I live in Paris","My name is Marie","I am a student","I speak French"],a:1,f:"Je m'appelle = My name is. Literally 'I call myself'."},
{q:"Which article is used for feminine nouns?",o:["Le","La","Les","Un"],a:1,f:"La is the feminine article. Le is masculine. Les is plural."},
{q:"What does 'S'il vous plait' mean?",o:["Thank you","Excuse me","Please","You're welcome"],a:2,f:"S'il vous plait = Please (formal). De rien = You're welcome."},
{q:"'Je ne comprends pas' means?",o:["I don't know","I don't have","I don't understand","I don't speak"],a:2,f:"Je ne comprends pas = I don't understand. Essential phrase for beginners."},
{q:"'Ou est la gare?' means?",o:["Where is the restaurant?","Where is the station?","Where is the hotel?","Where is the pharmacy?"],a:1,f:"Ou est = Where is. La gare = the train station."},
{q:"What is 'eau' in English?",o:["Milk","Wine","Water","Juice"],a:2,f:"Eau = Water. Lait = Milk. Vin = Wine. Jus = Juice."},
{q:"'Combien ca coute?' means?",o:["What is your name?","How much does it cost?","Where are you from?","What time is it?"],a:1,f:"Combien = how much. Ca coute = it costs."},
{q:"What does 'rouge' mean?",o:["Blue","Green","Red","Yellow"],a:2,f:"Rouge = Red. Bleu = Blue. Vert = Green. Jaune = Yellow."},
{q:"Which number is 'vingt'?",o:["10","15","20","25"],a:2,f:"Vingt = 20. French numbers are quirky: 70=soixante-dix, 80=quatre-vingts!"},
{q:"'J'ai faim' means?",o:["I'm thirsty","I'm tired","I'm hungry","I'm hot"],a:2,f:"J'ai faim = I'm hungry. French uses avoir (have) for physical states."},
{q:"'Excusez-moi' is used to say?",o:["Thank you","Goodbye","Excuse me","Help"],a:2,f:"Excusez-moi = Excuse me (formal). Excuse-moi = informal."},
{q:"What does 'maison' mean?",o:["School","Office","House","Market"],a:2,f:"Maison = House. Ecole = School. Bureau = Office."},
{q:"'Je voudrais un cafe' means?",o:["I want coffee","I would like a coffee","Give me coffee","A coffee, yes"],a:1,f:"Je voudrais = I would like (polite conditional form)."},
{q:"What is 'frere' in English?",o:["Sister","Mother","Brother","Father"],a:2,f:"Frere = Brother. Soeur = Sister. Mere = Mother. Pere = Father."},
{q:"What does 'petit' mean?",o:["Big","Fast","Small","Old"],a:2,f:"Petit = Small. Grand = Big. Rapide = Fast. Vieux = Old."},
{q:"'Au revoir' means?",o:["Hello","Goodbye","Please","Thank you"],a:1,f:"Au revoir = Goodbye. Literally 'until seeing again'."},
{q:"What is 'hopital' in English?",o:["School","Hospital","Hotel","Town hall"],a:1,f:"Hopital = Hospital. Don't confuse with Hotel!"}
],
intermediate:[
{q:"Which tense is 'Je mangeais'?",o:["Passe compose","Futur simple","Imparfait","Conditionnel"],a:2,f:"Imparfait = ongoing or habitual past. Je mangeais = I was eating / used to eat."},
{q:"What does TEF Canada test?",o:["Only written","Only spoken","All 4 skills (R/W/L/S)","Grammar only"],a:2,f:"TEF Canada tests Reading, Writing, Listening and Speaking. Required for Canada immigration."},
{q:"'Il faut que' + subjunctive is used after?",o:["Past actions","Necessity, doubt, emotion","Future plans","Descriptions"],a:1,f:"Subjunctive after expressions of necessity, doubt, and emotion."},
{q:"Which is correct for 'We went to France'?",o:["Nous sommes alles en France","Nous avons alle en France","Nous allions en France","Nous irons en France"],a:0,f:"Aller uses etre (not avoir) in passe compose. About 17 verbs use etre."},
{q:"What does 'se debrouiller' mean?",o:["To get lost","To manage / cope / get by","To escape","To disagree"],a:1,f:"Se debrouiller = to manage / get by. Je me debrouille en francais = I get by in French."},
{q:"What is the DELF B2 level?",o:["Elementary","Pre-intermediate","Upper-intermediate","Only basic communication"],a:2,f:"DELF B2 = Upper-Intermediate. Can communicate spontaneously in most situations."},
{q:"What is the difference between savoir and connaitre?",o:["Same usage","Savoir=know facts/how, Connaitre=know people/places","Savoir=people, Connaitre=facts","Connaitre is formal"],a:1,f:"Savoir = know facts/how to. Connaitre = know people/places (be familiar with)."},
{q:"Which is the correct comparative for 'better'?",o:["Plus bon","Meilleur","Mieux","Plus bien"],a:1,f:"Meilleur(e) = better (adjective). Mieux = better (adverb). Plus bon is incorrect."},
{q:"TEF Canada CLB 7 corresponds to which CEFR level?",o:["A2","B1","B2","C1"],a:2,f:"CLB 7 is approximately B2. Target for maximum Express Entry CRS points."},
{q:"'Quand meme' is best translated as?",o:["However / all the same","Immediately","Obviously","Apparently"],a:0,f:"Quand meme = however / all the same / anyway. Very common in conversation."},
{q:"What does DELF stand for?",o:["Diplome d'Etudes de Langue Francaise","Diplome d'Examen de Langue","Diplome d'Enseignement","Diplome d'Evaluation"],a:0,f:"DELF = Diplome d'Etudes en Langue Francaise. Valid for life (no expiry)."},
{q:"'Avoir beau + infinitif' means?",o:["To do in vain / no matter how much","To do beautifully","To barely do","To have just done"],a:0,f:"J'ai beau essayer = No matter how hard I try. Idiomatic and common."},
{q:"What is the futur anterieur used for?",o:["Action completed before another future action","Past continuous","Hypothetical present","Immediate future"],a:0,f:"Future perfect: action completed before another future action."},
{q:"'Au fur et a mesure' means?",o:["Little by little / as one goes along","Now and then","All at once","From the beginning"],a:0,f:"Au fur et a mesure = as one goes along / gradually. Very common expression."},
{q:"Si + present + futur expresses?",o:["Impossible condition","Hypothetical","Real condition (likely)","Past regret"],a:2,f:"Real condition: Si tu viens, je serai content = If you come, I will be happy."}
],
advanced:[
{q:"'Il n'empeche que' means?",o:["It follows that","It prevents that","Nevertheless / the fact remains that","It seems that"],a:2,f:"Il n'empeche que = nevertheless / the fact remains that. Formal argumentation."},
{q:"What is the difference between 'en' and 'y' as pronouns?",o:["En=location, y=quantity","En replaces de+noun, y replaces a+noun","Interchangeable","En=direct, y=indirect"],a:1,f:"En replaces de + noun. Y replaces a + noun/place. J'y vais = I'm going there."},
{q:"The gerondif 'en + present participle' expresses?",o:["Future","Simultaneous action / manner","Past","Completed action"],a:1,f:"Gerondif: en chantant (while singing). Simultaneous action or means."},
{q:"What is the passe simple used for?",o:["Everyday spoken past","Literary/formal written narrative past","Future narration","Hypothetical past"],a:1,f:"Passe simple is literary — never spoken, only in literature and formal writing."},
{q:"What does accord du participe passe refer to?",o:["Adjective agreement","Past participle agreement with subject/object","Verb agreement","Pronoun agreement"],a:1,f:"Past participle agrees with preceding direct object. Complex and tested in DALF."},
{q:"'C'est-a-dire' is used to introduce?",o:["A contradiction","A clarification (that is to say)","A consequence","A hypothesis"],a:1,f:"C'est-a-dire = that is to say / i.e. Used to clarify or reformulate."},
{q:"'Avoir le beurre et l'argent du beurre' means?",o:["To be wealthy","To want to have it both ways","To make a hard choice","To negotiate hard"],a:1,f:"= to want the butter and the money from the butter = have your cake and eat it too."},
{q:"'Nonobstant' is a formal connector meaning?",o:["Because of","Notwithstanding / Despite","Regarding","Furthermore"],a:1,f:"Nonobstant = notwithstanding / despite. Formal/legal. DALF C1/C2 vocabulary."},
{q:"'Quoiqu'il en soit' means?",o:["Although he is there","Be that as it may","However he does it","While he was doing it"],a:1,f:"Quoiqu'il en soit = be that as it may / whatever the case. Formal expression."},
{q:"What does 'queisme' refer to in grammar?",o:["Correct use of que","Error of using que when de que is required","Adding de que incorrectly","A subjunctive error"],a:1,f:"Queisme = error of omitting de before que. Correct: Estoy seguro de que vendra."},
{q:"'A titre indicatif' introduces information that is?",o:["Definitive","For information purposes / indicatively","Confidential","Mandatory"],a:1,f:"A titre indicatif = for information purposes. May change. Common in business French."}
]
},
german:{
basic:[
{q:"What does 'Guten Morgen' mean?",o:["Good evening","Good night","Good morning","Goodbye"],a:2,f:"Guten Morgen = Good morning. Guten Tag = Good day. Guten Abend = Good evening."},
{q:"'Wie heissen Sie?' means?",o:["How are you?","What is your name?","Where do you live?","How old are you?"],a:1,f:"Wie heissen Sie? = What is your name? (formal). Ich heisse... = My name is..."},
{q:"Which article is masculine in German?",o:["Die","Das","Den","Der"],a:3,f:"Der = masculine. Die = feminine. Das = neuter. German has 3 genders!"},
{q:"What does 'Danke schoen' mean?",o:["Please","You're welcome","Thank you very much","Excuse me"],a:2,f:"Danke schoen = Thank you very much. Bitte = Please / You're welcome."},
{q:"'Ich verstehe nicht' means?",o:["I don't want","I don't know","I don't understand","I can't see"],a:2,f:"Ich verstehe nicht = I don't understand."},
{q:"What is 'Wasser' in English?",o:["Fire","Air","Earth","Water"],a:3,f:"Wasser = Water. Cognate with English 'water'."},
{q:"'Wie viel kostet das?' means?",o:["What is this?","How much does it cost?","Where is this from?","Can I have this?"],a:1,f:"Wie viel kostet das? = How much does it cost?"},
{q:"What number is 'zehn'?",o:["7","8","9","10"],a:3,f:"Zehn = 10. Eins, zwei, drei, vier, fuenf, sechs, sieben, acht, neun, zehn."},
{q:"What does 'Entschuldigung' mean?",o:["Thank you","Please","Excuse me / Sorry","Hello"],a:2,f:"Entschuldigung = Excuse me / I'm sorry."},
{q:"'Sprechen Sie Englisch?' means?",o:["Do you speak German?","Can you help me?","Do you speak English?","Where are you from?"],a:2,f:"Sprechen Sie Englisch? = Do you speak English? (formal)."},
{q:"What is 'Krankenhaus' in English?",o:["School","Hotel","Hospital","Restaurant"],a:2,f:"Krankenhaus = Hospital. Kranken=sick, Haus=house. Compound noun!"},
{q:"'Ich moechte ein Bier, bitte' means?",o:["I don't like beer","I would like a beer, please","Beer is expensive","One more beer"],a:1,f:"Ich moechte = I would like (polite). Ein Bier = a beer."},
{q:"Which means 'big' in German?",o:["Klein","Schnell","Alt","Gross"],a:3,f:"Gross = Big. Klein = Small. Schnell = Fast. Alt = Old."},
{q:"What direction is 'links'?",o:["Right","Straight","Left","Up"],a:2,f:"Links = Left. Rechts = Right. Geradeaus = Straight ahead."},
{q:"'Wie geht es Ihnen?' means?",o:["Where do you work?","How old are you?","How are you?","What do you do?"],a:2,f:"Wie geht es Ihnen? = How are you? (formal). Mir geht es gut = I'm well."}
],
intermediate:[
{q:"What are the four German cases?",o:["M/F/N/Plural","Nominative/Accusative/Dative/Genitive","Subject/Object/Indirect/Possessive","Der/Die/Das/Den"],a:1,f:"4 cases change article forms: Nominative, Accusative, Dative, Genitive."},
{q:"Which Goethe level is needed for German university?",o:["A2","B1","B2/C1","C2"],a:2,f:"Most German universities require B2-C1 equivalent (TestDaF or Goethe)."},
{q:"'Ich habe gegessen' is which tense?",o:["Praeteritum","Perfekt","Futur","Plusquamperfekt"],a:1,f:"Perfekt = haben/sein + past participle. Used for most spoken past events."},
{q:"What is Ausbildung?",o:["University degree","Vocational training apprenticeship","Language course","Work permit"],a:1,f:"Ausbildung = dual vocational training. Learn at company AND vocational school."},
{q:"Which modal verb means 'must'?",o:["Koennen","Duerfen","Muessen","Sollen"],a:2,f:"Muessen = must. Koennen = can. Duerfen = may. Sollen = should."},
{q:"Where does the verb go in a subordinate clause?",o:["First","Second","At the end","After subject"],a:2,f:"In subordinate clauses (weil, dass, wenn), the verb goes to the END."},
{q:"What is Konjunktiv II used for?",o:["Past events","Commands","Hypothetical/Wishes/Polite requests","Future certainty"],a:2,f:"Konjunktiv II = hypothetical statements, wishes, polite requests."},
{q:"What does 'Gemuetlichkeit' mean?",o:["Melancholy","Cosy warmth and contentment","Efficiency","Hospitality"],a:1,f:"Gemuetlichkeit = cosiness, warmth, friendliness. Deeply cultural concept."},
{q:"Which preposition always takes dative?",o:["Fuer","Durch","Mit","Um"],a:2,f:"Mit always takes dative: mit dem Bus = by bus."},
{q:"What does 'es gibt' mean?",o:["It gives","He gives","There is/are","It belongs to"],a:2,f:"Es gibt = there is / there are (+ accusative). Always singular form."},
{q:"'Wegen des schlechten Wetters' uses which case?",o:["Accusative","Nominative","Genitive","Dative"],a:2,f:"Wegen (because of) governs Genitive case."},
{q:"What does 'Wanderlust' mean?",o:["Homesickness","Strong desire for travel","Local patriotism","Fear of open spaces"],a:1,f:"Wanderlust = strong desire to travel. A German word used worldwide."},
{q:"Seit vs Vor: what's the difference?",o:["Both mean since","Seit=since/for (ongoing), Vor=ago (completed)","Seit=ago, Vor=since","Interchangeable"],a:1,f:"Seit + present = since/for (ongoing). Vor = ago (completed past action)."},
{q:"What is 'Fachkraeftemangel'?",o:["Surplus of workers","Skilled worker shortage","Training programme","Economic growth"],a:1,f:"Fachkraeftemangel = skilled worker shortage. Germany actively recruits internationally."},
{q:"Which German exam is for work/Ausbildung immigration?",o:["Goethe-Zertifikat","TestDaF","Telc Deutsch Beruf","DELF"],a:2,f:"Telc Deutsch Beruf = Workplace German, specifically for professional contexts."}
],
advanced:[
{q:"What is Konjunktiv I used for?",o:["Hypothetical wishes","Indirect/reported speech","Polite requests","Passive voice"],a:1,f:"Konjunktiv I = indirect speech in formal/journalistic writing."},
{q:"What is 'Nominalstil'?",o:["Using only nouns","Transforming verbal expressions into noun phrases","Avoiding adjectives","Writing without articles"],a:1,f:"Nominalstil = nominalization. Characteristic of formal, academic German. C1/C2 skill."},
{q:"'Ohne + zu + Infinitiv' expresses?",o:["Without doing something","Instead of doing","In order to do","While doing"],a:0,f:"Ohne zu + Infinitiv: Er ging, ohne zu gruessen = He left without greeting."},
{q:"What does 'zwar... aber' express?",o:["Either... or","Both... and","Admittedly... but","Neither... nor"],a:2,f:"Zwar... aber = admittedly... but. Concession + contrast. C1 discourse."},
{q:"What is a 'Funktionsverbgefuege'?",o:["Compound noun","Light verb construction (verb+noun as one unit)","Reflexive verb","Separable verb"],a:1,f:"FVG = light verb constructions: eine Entscheidung treffen (=entscheiden). Common in formal German."},
{q:"'Nichtsdestotrotz' means?",o:["Furthermore","Nevertheless","Instead","On the contrary"],a:1,f:"Nichtsdestotrotz = nevertheless. One of German's longest common words."},
{q:"What does modal particle 'doch' express?",o:["Uncertainty","Agreement, reassurance, or contradiction","Possibility","Time"],a:1,f:"Doch = agreement/reassurance or contradiction of a negative assumption. Very German!"},
{q:"'Inwiefern' introduces?",o:["Extent / in what way","A time clause","A reason","A concession"],a:0,f:"Inwiefern = in what way / to what extent. Used in analytical questioning."},
{q:"What is 'Vergangenheitsbewaeltigung'?",o:["A grammar tense","Coming to terms with the past (esp. WWII)","Regional dialect","Compound noun type"],a:1,f:"= coming to terms with the past. A key German cultural concept about confronting history."},
{q:"Passiv mit Modalverb construction is?",o:["Modal + werden + infinitive","Modal + past participle + werden","Sein + past participle","Haben + past participle"],a:1,f:"Das Problem muss geloest werden = The problem must be solved."},
{q:"'Im Hinblick auf' means?",o:["Looking back on","With regard to / In view of","On behalf of","Despite"],a:1,f:"Im Hinblick auf = with regard to. Formal connector. Similar: In Bezug auf, Hinsichtlich."}
]
},
korean:{
basic:[
{q:"How do you say 'Hello' in Korean?",o:["Gamsahamnida","Annyeonghaseyo","Juseyo","Joesonghamnida"],a:1,f:"Annyeonghaseyo = Hello (formal). Annyeong = Hi (informal)."},
{q:"What does 'gamsahamnida' mean?",o:["Goodbye","Please","Excuse me","Thank you"],a:3,f:"Gamsahamnida = Thank you (formal). Gomawoyo = Thank you (informal)."},
{q:"Which script does Korean use?",o:["Kanji","Hiragana","Hangul","Roman alphabet"],a:2,f:"Hangul was created by King Sejong in 1443. 24 letters, very logical and systematic!"},
{q:"What does 'ne' mean?",o:["No","Maybe","Please","Yes"],a:3,f:"Ne = Yes. Aniyo = No. Be careful: ne? with rising tone = Pardon?"},
{q:"'Eolmayeyo?' means?",o:["What is this?","Where is this?","How much is it?","When?"],a:2,f:"Eolmayeyo? = How much is it? Essential for shopping!"},
{q:"The Korean word 'mul' means?",o:["Fire","Water","Tree","Wind"],a:1,f:"Mul = Water. Bul = Fire."},
{q:"'Hwajangsil-i eodiyeyo?' means?",o:["Where is the hospital?","Where is the exit?","Where is the toilet?","Where is the hotel?"],a:2,f:"Hwajangsil = restroom. Eodiyeyo = where is? Literally 'make-up room'!"},
{q:"What does 'aigo' express?",o:["Greeting","Farewell","Exclamation of surprise/distress","Agreement"],a:2,f:"Aigo! = Oh my! / Oh no! You'll hear it constantly in Korean daily life!"},
{q:"'Massisseoyo' means?",o:["I'm full","It's cheap","It's delicious","It's spicy"],a:2,f:"Massisseoyo = Delicious! One of the most important Korean food phrases!"},
{q:"What does EPS-TOPIK stand for?",o:["English Proficiency Standard","Employment Permit System-Test of Proficiency in Korean","Extended Placement System","Elementary Placement Standard"],a:1,f:"EPS-TOPIK = mandatory Korean test for work visa in Korea. DIFL has Rajasthan's highest pass rate."},
{q:"'Juseyo' is used to?",o:["Say hello","Ask a question","Request something (please give me)","Say goodbye"],a:2,f:"Juseyo = Please give me. Mul juseyo = Water please. Incredibly useful!"},
{q:"'Jihacheol' means?",o:["Bus","Train","Subway/Metro","Taxi"],a:2,f:"Jihacheol = Subway/Metro. Seoul's metro is world-famous for cleanliness."},
{q:"How do you say 'I'm sorry' formally?",o:["Gamsahamnida","Joesonghamnida","Gwaenchanayo","Jamkkanmanyo"],a:1,f:"Joesonghamnida = I'm sorry (formal). Mianhaeyo = Sorry (informal)."},
{q:"What is kimchi?",o:["A greeting","Korean currency","Fermented vegetable dish","A drink"],a:2,f:"Kimchi = Korea's national dish. Fermented vegetables, 200+ varieties. UNESCO-listed!"},
{q:"'Gwaenchanayo' means?",o:["Help me!","Delicious","It's okay / I'm fine","Please wait"],a:2,f:"Gwaenchanayo = It's okay / I'm fine / No problem. Very versatile!"}
],
intermediate:[
{q:"What is the difference between i/ga and eun/neun?",o:["No difference","i/ga=subject marker, eun/neun=topic marker","i/ga=object, eun/neun=subject","i/ga is formal"],a:1,f:"i/ga marks grammatical subject (new info). eun/neun marks topic (known info or contrast)."},
{q:"What does TOPIK II test?",o:["Beginners (levels 1-2)","Intermediate to advanced (levels 3-6)","Only writing","Only speaking"],a:1,f:"TOPIK II covers levels 3-6. For GKS Scholarship, TOPIK 3 minimum."},
{q:"Which verb ending indicates 'because'?",o:["-go","-aseo/eoseo","-jiman","-myeon"],a:1,f:"-aseo/eoseo = because/so. Bi-ga waseo mot gasseyo = Because it rained, couldn't go."},
{q:"What is jondaetmal used for?",o:["Talking to friends","Talking to strangers, elders, superiors","Only in writing","Only on the phone"],a:1,f:"Jondaetmal = honorific/polite speech. Korean has 6 speech levels!"},
{q:"'Hal su isseoyo' means?",o:["I want to","I must","I can do it","I will do it"],a:2,f:"= can/be able to. Hal su eopseoyo = cannot do."},
{q:"What is Korean age counting?",o:["Same as international","Korean age = international + 1","Korean age = international - 1","Counts from first birthday"],a:1,f:"Everyone is 1 at birth. Korea officially adopted international age in 2023."},
{q:"Which honorific replaces meokda (eat) for elders?",o:["Deushida/Jabsushida","Meogushida","Deurida","Jushida"],a:0,f:"Deushida/Jabsushida = honorific of eat. Essential in Korean polite speech."},
{q:"GKS scholarship requires minimum TOPIK level?",o:["No Korean required","TOPIK 1","TOPIK 3","TOPIK 5"],a:2,f:"GKS typically requires TOPIK 3 for undergraduate programs."},
{q:"What does 'baedalL' mean?",o:["K-pop concert","Delivery (food)","Market","Restaurant"],a:1,f:"Baedalr = delivery. Korea has one of the world's best delivery cultures."},
{q:"What is Nunchi?",o:["Traditional music","Ability to read the room / sense social cues","Table manners","Respectful bowing"],a:1,f:"Nunchi = the subtle art of gauging others' feelings. Deeply embedded in Korean culture."},
{q:"'-a/eo boda' expresses?",o:["To see something","Try doing something","To look at","To pretend"],a:1,f:"-a/eo boda = try doing. Meogeo bwasseyo = I tried eating it."},
{q:"What is Hallyu?",o:["Korean language","The Korean Wave (global spread of Korean culture)","Traditional music","Korean economy"],a:1,f:"Hallyu = The Korean Wave. K-pop, K-drama, Korean food spreading globally."},
{q:"'Siksahasyeosseyo?' is often used as?",o:["Medical question","A casual greeting (Have you eaten?)","Restaurant request","Formal invitation"],a:1,f:"= Have you eaten? Commonly used as a greeting. Food is central to Korean culture."},
{q:"EPS-TOPIK tests Korean for which context?",o:["Academic","Tourist","Workplace (manufacturing/industrial)","Formal business"],a:2,f:"EPS-TOPIK tests workplace Korean: factory instructions, safety signs, work orders."},
{q:"What does 'uri' culturally express?",o:["I/me","You","Our/We (collectivism)","They"],a:2,f:"Uri = our/we. Reflects collectivist culture. Uri eomma = our mom (not my mom)."}
],
advanced:[
{q:"'-neunde/eunde' at clause end expresses?",o:["Strong certainty","Background info / soft contrast","Completed action","Future intention"],a:1,f:"-neunde provides background context or soft contrast. Also softens statements."},
{q:"'-(eu)ryeogo hada' expresses?",o:["Just finished","Intend to / be going to","Accidentally did","Regret doing"],a:1,f:"-(eu)ryeogo hada = intend to / about to do."},
{q:"'-myeon an dwaeyo' expresses?",o:["It's okay to","You must do","You must not / not allowed","You should do"],a:2,f:"= must not / not allowed. Yeogiseo sajin jjigeumyeon an dwaeyo = No photos here."},
{q:"What is 'ppalli ppalli' culture?",o:["Slow food movement","Culture of speed and efficiency","Punctuality","Work-life balance"],a:1,f:"Ppalli ppalli = hurry hurry. Korea's culture of speed credited for rapid development."},
{q:"Which particle marks indirect object?",o:["eul/reul","i/ga","ege/hante","eseo"],a:2,f:"Ege/hante = to (indirect object, for people). Hante is more colloquial."},
{q:"What is 'PC bang' in Korean culture?",o:["A coffee shop","Internet gaming cafe (24-hour)","A library","A work centre"],a:1,f:"PC bang = internet gaming cafe. Open 24 hours. Iconic part of Korean youth culture."},
{q:"'-n ji + time + dwaeyo' expresses?",o:["Will do for (time)","It has been (time) since doing","Did (time) ago","Plans for (time)"],a:1,f:"= It has been [time] since doing. Baeun ji 1-nyeon-i dwaesseyo = 1 year since I started learning."},
{q:"What number system is used for time?",o:["Sino-Korean only","Pure Korean for hours, Sino-Korean for minutes","Pure Korean only","Either works"],a:1,f:"Hours use pure Korean (han si = 1 o'clock). Minutes use Sino-Korean (o bun = 5 minutes)."},
{q:"'Eotteoke saenggakhaeyo?' means?",o:["How do you feel?","What do you think?","What do you want?","How are you doing?"],a:1,f:"= What do you think? Very useful for conversations and debates."},
{q:"What does honorific suffix 'nim' express?",o:["Plural","Feminine","Respect/Honorific","Past tense"],a:2,f:"Nim = honorific suffix. Seonsaengnim = teacher (respected). Gogaengnim = valued customer."}
]
},
spanish:{
basic:[
{q:"What does 'Buenos dias' mean?",o:["Good evening","Good night","Good morning","Goodbye"],a:2,f:"Buenos dias = Good morning. Buenas tardes = Good afternoon. Buenas noches = Good night."},
{q:"'Como te llamas?' means?",o:["How are you?","Where are you from?","What is your name?","How old are you?"],a:2,f:"Como te llamas? = What's your name? Me llamo... = My name is..."},
{q:"What does 'Por favor' mean?",o:["Thank you","You're welcome","Please","Excuse me"],a:2,f:"Por favor = Please. Gracias = Thank you. De nada = You're welcome."},
{q:"'No entiendo' means?",o:["I don't know","I don't want","I don't understand","I can't see"],a:2,f:"No entiendo = I don't understand. No se = I don't know."},
{q:"What is 'agua'?",o:["Fire","Air","Water","Earth"],a:2,f:"Agua = Water. Fuego = Fire. Aire = Air. Tierra = Earth."},
{q:"'Cuanto cuesta?' means?",o:["What time?","Where is it?","How much does it cost?","What is this?"],a:2,f:"Cuanto cuesta? = How much does it cost?"},
{q:"What does 'rojo' mean?",o:["Blue","Green","Red","Yellow"],a:2,f:"Rojo = Red. Azul = Blue. Verde = Green. Amarillo = Yellow."},
{q:"Spanish has two verbs for 'to be'. Which?",o:["Estar and Tener","Ser and Estar","Ser and Haber","Estar and Haber"],a:1,f:"Ser (permanent) and Estar (temporary) both mean 'to be'. Critical distinction!"},
{q:"'Me gusta el cafe' means?",o:["I make coffee","I want coffee","I like coffee","I drink coffee"],a:2,f:"Me gusta = I like (literally 'it pleases me')."},
{q:"'Tengo hambre' means?",o:["I'm thirsty","I'm cold","I'm hungry","I'm hot"],a:2,f:"Tengo hambre = I'm hungry. Spanish uses tener (have) for physical states."},
{q:"What is DELE?",o:["A festival","Official Spanish language certification","A university","A learning app"],a:1,f:"DELE = Diplomas de Espanol. Official from Instituto Cervantes. Valid for life."},
{q:"'Donde esta el bano?' means?",o:["Where is the restaurant?","Where is the hotel?","Where is the bathroom?","Where is the exit?"],a:2,f:"Donde esta = Where is. El bano = the bathroom."},
{q:"'Hasta luego' means?",o:["Hello","Thank you","See you later","Please"],a:2,f:"Hasta luego = See you later. Hasta pronto = See you soon."},
{q:"Which is NOT a Spanish-speaking country?",o:["Argentina","Colombia","Brazil","Mexico"],a:2,f:"Brazil speaks Portuguese! 20 countries speak Spanish."},
{q:"'Mucho gusto' is said when?",o:["Saying goodbye","Ordering food","Meeting someone (Nice to meet you)","Thanking someone"],a:2,f:"Mucho gusto = Nice to meet you. Literally 'Much pleasure.'"}
],
intermediate:[
{q:"What's the difference between por and para?",o:["Interchangeable","Por=cause/means/duration, Para=purpose/destination/deadline","Por=destination, Para=cause","Por is formal"],a:1,f:"Por: cause, means, duration. Para: purpose, destination, deadline."},
{q:"DELE B2 is which professional level?",o:["Elementary","Pre-intermediate","Upper-intermediate","Only basic"],a:2,f:"DELE B2 = Upper-Intermediate. Can communicate spontaneously in most situations."},
{q:"'Si tuviera dinero, compraria un coche' uses?",o:["Present + Future","Imperfect subjunctive + Conditional","Past + Future","Subjunctive present + Conditional"],a:1,f:"Hypothetical condition: Si + imperfect subjunctive, conditional."},
{q:"What does 'a pesar de que' introduce?",o:["A reason","A condition","A concession (despite)","A result"],a:2,f:"A pesar de que = despite the fact that / although."},
{q:"'Llevar + gerundio' expresses?",o:["Just finished","About to do","Duration of ongoing action","Planning to do"],a:2,f:"Llevo tres anos estudiando = I have been studying for 3 years."},
{q:"What's the difference between conocer and saber?",o:["Same","Saber=facts/how, Conocer=people/places","Saber=people, Conocer=facts","Conocer is formal"],a:1,f:"Saber = know facts/how to. Conocer = know people/places (be familiar with)."},
{q:"'Acabar de + infinitivo' expresses?",o:["Finish doing","Be about to","To have just done","Want to do"],a:2,f:"Acabar de = to have just done. Acabo de llegar = I have just arrived."},
{q:"Which tense combination narrates past events?",o:["Imperfecto + Indefinido","Present + Past","Future + Imperfect","All past tenses are same"],a:0,f:"Imperfecto (background/ongoing) + Indefinido (completed events). Classic combination."},
{q:"'Sin embargo' means?",o:["Therefore","However / Nevertheless","Furthermore","Although"],a:1,f:"Sin embargo = however / nevertheless. Very common connector."},
{q:"What does 'ojala' come from?",o:["Latin","Greek","Arabic (Inshallah)","French"],a:2,f:"Ojala comes from Arabic 'Inshallah' (if God wills). Ojala + subjunctive = I hope/wish."},
{q:"What is 'vosotros'?",o:["Formal you (singular)","Informal you-all (plural) — Spain only","Formal you-all","Used everywhere in Spanish world"],a:1,f:"Vosotros = informal plural you. Used ONLY in Spain. Latin America uses ustedes."},
{q:"'Aunque + subjuntivo' vs indicativo?",o:["No difference","Subjunctive=even if (hypothetical), Indicative=even though (fact)","Subjunctive is formal","Indicative for future"],a:1,f:"Aunque + indicative = even though (fact). Aunque + subjunctive = even if (hypothetical)."},
{q:"'Cuanto mas, mejor' means?",o:["As much as possible","The more, the better","More or less","Too much is bad"],a:1,f:"Cuanto mas... mas... = the more... the more... Cuanto antes, mejor = the sooner the better."},
{q:"What does 'ponerse' express vs 'estar'?",o:["To be (permanent)","To become (change of state)","To put on clothes","To place something"],a:1,f:"Ponerse = to become (change of state). Me puse nervioso = I became nervous."}
],
advanced:[
{q:"'No bien... cuando' expresses?",o:["Neither... nor","No sooner... than","Although... yet","If... then"],a:1,f:"No bien... cuando = no sooner... than. Immediate sequence of actions."},
{q:"'A tenor de' means?",o:["Despite","In the light of / According to","Instead of","Concerning"],a:1,f:"A tenor de = in the light of / according to. Formal written register."},
{q:"'Habida cuenta de que' means?",o:["In order that","Taking into account that","Whereas","Despite"],a:1,f:"Habida cuenta de que = taking into account that / given that. Formal/bureaucratic."},
{q:"Third conditional uses?",o:["What would happen","Pluperfect subjunctive + Conditional perfect","Current hypothesis","Future possibility"],a:1,f:"Si hubiera estudiado, habria aprobado = If I had studied, I would have passed."},
{q:"'Por si las moscas' means?",o:["Because of flies","Just in case","Due to bad luck","No matter what"],a:1,f:"Por si las moscas = just in case. Literal: in case of flies. Very common idiom."},
{q:"'Al + infinitivo' expresses?",o:["Purpose","Upon doing / When","In order to","Instead of"],a:1,f:"Al + infinitivo = upon/when doing. Al llegar a casa = Upon arriving home."},
{q:"What is 'voz pasiva refleja'?",o:["Reflexive actions","Impersonal/passive with se (se vende, se habla)","Reciprocal actions","Emphasizing subject"],a:1,f:"Se venden pisos = Flats are sold. Se habla espanol = Spanish is spoken."},
{q:"'A grandes rasgos' means?",o:["In great detail","At full speed","In broad strokes / Broadly speaking","With great effort"],a:2,f:"A grandes rasgos = broadly speaking / in general terms. Common in professional discourse."},
{q:"'Sin ir mas lejos' is used to?",o:["Go no further than a close example","Without any doubt","Without explanation","Immediately"],a:0,f:"Sin ir mas lejos = as a case in point / without going further."},
{q:"What does 'queismo' refer to?",o:["Correct use of que","Error of using que when de que is needed","Adding de que incorrectly","Subjunctive error"],a:1,f:"Queismo = omitting de before que. Correct: Estoy seguro de que vendra."}
]
},
chinese:{
basic:[
{q:"What does 'ni hao' mean?",o:["Thank you","Goodbye","Hello","Please"],a:2,f:"Ni hao = Hello. Ni = you, Hao = good."},
{q:"How do you say 'Thank you' in Mandarin?",o:["Duibuqi","Zaijian","Xiexie","Qing"],a:2,f:"Xiexie = Thank you. Duibuqi = Sorry. Zaijian = Goodbye. Qing = Please."},
{q:"'Duoshao qian?' means?",o:["Where is it?","What time?","How much does it cost?","What is this?"],a:2,f:"Duoshao qian = How much money? Essential for shopping!"},
{q:"What is 'shui' in English?",o:["Fire","Water","Earth","Wood"],a:1,f:"Shui = Water. Huo = Fire. Tu = Earth. Mu = Wood."},
{q:"How many tones does Mandarin have?",o:["2","3","4","5"],a:2,f:"4 tones plus neutral. Same sound, different tone = different meaning. Ma can mean mother, hemp, horse, or scold!"},
{q:"What does 'hao chi' mean?",o:["Looks good","Smells good","Delicious","Expensive"],a:2,f:"Hao chi = delicious. Hao = good, Chi = eat."},
{q:"What writing system does Mandarin use?",o:["Hiragana","Hangul","Alphabet","Chinese characters (Hanzi)"],a:3,f:"Chinese uses Hanzi. About 50,000 characters but only ~3,000 needed for fluency."},
{q:"What is Pinyin?",o:["Traditional characters","A dialect","Romanization system for pronunciation","A measure word"],a:2,f:"Pinyin = official romanization system created in 1950s."},
{q:"'Mei you' means?",o:["I have","Not yet","Don't have / There is no","Not good"],a:2,f:"Mei you = don't have / there isn't. Negative of you (have)."},
{q:"What is HSK?",o:["University system","Chinese language exam for foreigners","Cultural festival","Business certification"],a:1,f:"HSK = Chinese Proficiency Test. Levels 1-6. Required for Chinese university admission."},
{q:"'Qing wen' is used before?",o:["Saying goodbye","A polite question (May I ask...)","Ordering food","Thanking someone"],a:1,f:"Qing wen = May I ask... Very polite way to begin a question."},
{q:"What does 'jia you' mean?",o:["Add oil / Go! / You can do it!","Good luck","Be careful","Well done"],a:0,f:"Jia you = Add oil! Used as encouragement: Go! / Come on! / You can do it!"},
{q:"How do you say 'China' in Mandarin?",o:["Riben","Zhongguo","Hanguo","Yindu"],a:1,f:"Zhongguo = China. Literally 'Middle Kingdom'. Riben = Japan, Hanguo = Korea."},
{q:"What does Shanghai mean literally?",o:["Northern sea","Eastern city","Above the sea","Great harbour"],a:2,f:"Shang = above/upon, Hai = sea. Shanghai = Upon the sea."},
{q:"'Yi dianr' means?",o:["A lot","Too much","A little bit","Nothing"],a:2,f:"Yi dianr = a little bit. Wo hui shuo yi dianr Zhongwen = I speak a little Chinese."}
],
intermediate:[
{q:"What is the Chinese root system based on?",o:["Alphabet","Radicals — components that indicate meaning categories","Vowels","Tones only"],a:1,f:"Chinese characters contain radicals indicating meaning. Water radical appears in river, lake, ocean etc."},
{q:"Which measure word is used for flat objects?",o:["Ge","Zhang","Ben","Ba"],a:1,f:"Zhang = flat objects (paper, photos). Ge is the default/general measure word."},
{q:"'Le' particle at end of sentence indicates?",o:["Question","Completed action / change of state","Negation","Continuation"],a:1,f:"Le indicates completed action or change of state. Wo chi le = I ate / I have eaten."},
{q:"What does 'ke yi' mean?",o:["Must","Want to","Can / May","Should"],a:2,f:"Ke yi = can / may (permission). Wo ke yi ma? = May I? Neng = can (ability)."},
{q:"HSK 4 is approximately which CEFR level?",o:["A1","A2","B2","C1"],a:2,f:"HSK 4 is approximately B2. Can discuss a wide range of topics with native speakers."},
{q:"'Sui ran... dan shi' means?",o:["Because... therefore","Although... but","If... then","Not only... but also"],a:1,f:"Suiran... danshi = although... but. Classic concessive structure in Chinese."},
{q:"What are the four great inventions of China?",o:["Tea, silk, porcelain, rice","Paper, printing, compass, gunpowder","Calligraphy, painting, poetry, music","Noodles, tofu, soy sauce, chopsticks"],a:1,f:"Si da faming: paper, printing, compass, gunpowder. Cultural pride in Chinese education."},
{q:"'Ba' construction is used for?",o:["Questions","Disposing of or doing something to a specific object","Past tense","Passive voice"],a:1,f:"Ba + object + verb: Wo ba shu fang zai zhuozi shang = I put the book on the table. Disposal construction."},
{q:"What does 'guanxi' mean in Chinese business?",o:["Money","Relationships / social connections","Contract","Negotiation"],a:1,f:"Guanxi = relationships/connections. Central to Chinese business. Building guanxi is essential for trade."},
{q:"'Yinwei... suoyi' means?",o:["Although... but","Because... therefore","If... then","Not only... but also"],a:1,f:"Yinwei... suoyi = because... therefore. Paired conjunction for cause-effect."},
{q:"What is the difference between 'shi' and 'you'?",o:["Same meaning","Shi=to be (identity), You=to have/exist","Shi=to have, You=to be","Shi is formal, You is informal"],a:1,f:"Shi = to be (identity/definition). You = to have/to exist. Fundamental distinction."},
{q:"'De' has three written forms. What are they?",o:["Same character always","De (possessive), De (adverbial), De (complement)","Only two forms","De has no written form"],a:1,f:"De has 3 forms: possessive, adverbial (manner), complement (result/degree). Critical grammar point."}
],
advanced:[
{q:"What does 'chengyu' refer to?",o:["A Chinese dialect","Four-character idiomatic expressions from classical Chinese","A type of character","Modern slang"],a:1,f:"Chengyu = 4-character idioms. Thousands exist from classical literature. HSK 5-6 tests many."},
{q:"'Bei' construction expresses?",o:["Active voice","Passive voice (often with negative connotation)","Imperative","Conditional"],a:1,f:"Bei = passive voice, often (not always) negative: Wo bei piping le = I was criticized."},
{q:"What is 'mianzi' in Chinese culture?",o:["A type of noodle","Face / social reputation and dignity","A greeting","A business card"],a:1,f:"Mianzi = face. Protecting, giving, and losing face are central to Chinese social dynamics."},
{q:"'Lian... dou/ye' pattern means?",o:["Both... and","Even... also (emphasizing surprising inclusion)","Neither... nor","Not only... but also"],a:1,f:"Lian... dou/ye = even... Lian ta dou zhidao = Even he knows. Emphasis on surprise."},
{q:"What is Classical Chinese (wenyan)?",o:["Modern spoken Chinese","Ancient literary Chinese still used in formal/academic contexts","A Chinese dialect","Simplified characters"],a:1,f:"Wenyan = Classical Chinese. Used in ancient texts, still appears in formal writing and chengyu."},
{q:"'Yi lai... er lai' expresses?",o:["One... two","On one hand... on the other hand","First come... then come","If... then"],a:1,f:"Yi lai... er lai = firstly... secondly / on one hand... on the other. Formal enumeration."},
{q:"What is the 'complement of result' in Chinese grammar?",o:["A separate sentence","A verb suffix showing result/completion of action","An adjective","A noun classifier"],a:1,f:"Result complement: Verb + result. Ting dong le = listened and understood. Kan wan le = read and finished."},
{q:"'Suowei' means?",o:["Therefore","So-called / what is known as","Because","However"],a:1,f:"Suowei = so-called / what is known as. Suowei de 'zhongguo meng' = the so-called 'Chinese Dream'."},
{q:"What does 'yin yang' represent?",o:["Good and evil","Complementary opposing forces in balance","Day and night only","Hot and cold only"],a:1,f:"Yin yang = complementary opposites in balance. Yin=dark/passive, Yang=light/active. Fundamental Chinese philosophy."}
]
},
italian:{
basic:[
{q:"What does 'Ciao' mean?",o:["Thank you","Please","Hi / Bye","Sorry"],a:2,f:"Ciao = Hi / Bye (informal). Buongiorno = Good morning. Arrivederci = Goodbye (formal)."},
{q:"'Grazie mille' means?",o:["Hello","You're welcome","Thank you very much","Good luck"],a:2,f:"Grazie mille = Thank you very much (literally 'a thousand thanks')."},
{q:"What is 'acqua' in English?",o:["Wine","Milk","Water","Coffee"],a:2,f:"Acqua = Water. Italy is famous for mineral water — naturale (still) or frizzante (sparkling)!"},
{q:"'Quanto costa?' means?",o:["Where is it?","What time?","How much does it cost?","What is this?"],a:2,f:"Quanto costa? = How much does it cost?"},
{q:"What is CILS?",o:["Cooking certification","Italian language certification (University of Siena)","Cultural institute","Music school"],a:1,f:"CILS = Italian language certification. Accepted for Italy work/study visas."},
{q:"What does Flussi Decree relate to?",o:["Italian rivers","Italian currency","Italy's seasonal work visa quota","Regional elections"],a:2,f:"Decreto Flussi = Italy's annual work visa quota for non-EU workers. Popular in Rajasthan."},
{q:"What does 'bello/bella' mean?",o:["Ugly","Beautiful","Big","Small"],a:1,f:"Bello (m) / Bella (f) = Beautiful."},
{q:"'Dov'e il bagno?' means?",o:["Where is the restaurant?","Where is the bathroom?","Where is the exit?","Where is the station?"],a:1,f:"Dov'e = Where is. Il bagno = the bathroom."},
{q:"'Per favore' means?",o:["Thank you","Excuse me","Please","You're welcome"],a:2,f:"Per favore = Please."},
{q:"What does 'Mangiamo!' mean?",o:["Let's sleep!","Let's drink!","Let's dance!","Let's eat!"],a:3,f:"Mangiamo! = Let's eat! Food is central to Italian culture."},
{q:"What is 'un caffe' in Italy?",o:["Large coffee with milk","Medium coffee","Small strong espresso","Decaf"],a:2,f:"Un caffe = espresso. Italians find it strange to order cappuccino after 11am!"},
{q:"How do you say 'I am Indian' in Italian?",o:["Sono di India","Sono indiano/indiana","Vengo a India","Sono dall'India"],a:1,f:"Sono indiano (m) / indiana (f) = I am Indian."},
{q:"'Buon appetito!' means?",o:["Have a good trip!","Enjoy your meal!","Happy birthday!","Good luck!"],a:1,f:"Buon appetito! = Enjoy your meal! The response is 'Grazie, altrettanto!'"},
{q:"What does 'famiglia' mean?",o:["Friends","Family","School","Work"],a:1,f:"Famiglia = Family. Central to Italian culture."},
{q:"'Scusa' vs 'Scusi' difference?",o:["Same, different regions","Scusa=informal, Scusi=formal","Scusa=bigger apology","For different situations"],a:1,f:"Scusa = informal (tu-form). Scusi = formal (Lei-form)."}
],
intermediate:[
{q:"Which CILS level is needed for Flussi work visa?",o:["A1","A2-B1","C1","No level needed"],a:1,f:"Italian A2-B1 is mandatory for most Flussi employers. DIFL offers CILS coaching."},
{q:"What is the passato prossimo?",o:["Simple past","Present perfect (avere/essere + past participle)","Future","Conditional"],a:1,f:"Passato prossimo = avere/essere + past participle. Ho mangiato = I ate / have eaten."},
{q:"Which verbs use 'essere' as auxiliary?",o:["Action verbs","Movement and state-change verbs","All verbs","Only reflexive verbs"],a:1,f:"Essere with: andare, venire, partire, arrivare, nascere, morire + reflexives."},
{q:"'Magari!' expresses?",o:["Certainly not","If only! / I wish! / Maybe (hopeful)","Never","Impossible"],a:1,f:"Magari = If only! / I wish! Also used as hopeful 'maybe'. Very common Italian expression."},
{q:"What does 'fare bella figura' mean?",o:["To make a painting","To make a good impression","To lose weight","To be famous"],a:1,f:"Fare bella figura = make a good impression. Central Italian cultural concept. Brutta figura = bad impression."},
{q:"Congiuntivo (subjunctive) is used after?",o:["Certainty","Opinions, wishes, doubts, emotions","Statements of fact","Past events"],a:1,f:"Congiuntivo after: penso che, credo che, spero che, bisogna che. Penso che sia vero."},
{q:"'Ce la faccio' means?",o:["I give up","I can manage / I can do it","I'm leaving","I don't care"],a:1,f:"Ce la faccio = I can do it / I can manage. Non ce la faccio = I can't cope/manage."},
{q:"What is the difference between sapere and conoscere?",o:["Same","Sapere=know facts/how, Conoscere=know people/places","Sapere=people, Conoscere=facts","Regional difference"],a:1,f:"Sapere = know facts, know how to. Conoscere = know/be familiar with people/places."},
{q:"'Nonostante' introduces?",o:["A reason","A concession (despite/although)","A consequence","A purpose"],a:1,f:"Nonostante = despite / although + subjunctive. Nonostante piova = Despite the rain."},
{q:"What does 'PLIDA' stand for?",o:["Italian music certification","Progetto Lingua Italiana Dante Alighieri","Professional Legal Italian Diploma","Practical Language Italian Department"],a:1,f:"PLIDA = Italian certification by Dante Alighieri Society. Alternative to CILS. Both accepted for visas."}
],
advanced:[
{q:"What is 'il periodo ipotetico del terzo tipo'?",o:["First conditional","Second conditional","Third conditional (impossible past)","Zero conditional"],a:2,f:"Se avessi studiato, avrei superato = If I had studied, I would have passed. Unrealised past."},
{q:"'Pur + gerundio' expresses?",o:["Purpose","Although / Even though + verb-ing","Because","Before doing"],a:1,f:"Pur sapendo la verita = Although knowing the truth. Concessive + gerund."},
{q:"What does 'atteso che' mean in formal Italian?",o:["In order that","Given that / Considering that","Despite","Instead of"],a:1,f:"Atteso che = given that / considering that. Legal/bureaucratic register. C1 connector."},
{q:"'Ci vuole' vs 'Ci vogliono' differs by?",o:["Formality","Singular vs plural subject (time/resources needed)","Tense","Negation"],a:1,f:"Ci vuole un'ora = One hour is needed. Ci vogliono due ore = Two hours are needed. Singular vs plural."},
{q:"What is the 'trapassato remoto'?",o:["A dialectal form","Past anterior (dopo che ebbe finito...)","A future tense","The gerund"],a:1,f:"Trapassato remoto = literary past anterior. Dopo che ebbe finito, parti. Used in formal written narration with passato remoto."},
{q:"'A prescindere da' means?",o:["Because of","Regardless of / Irrespective of","In addition to","According to"],a:1,f:"A prescindere da = regardless of / irrespective of. A prescindere dalle difficolta = regardless of difficulties."},
{q:"What is 'congiuntivo imperfetto' used for?",o:["Real conditions","Hypothetical present/future situations (if I were...)","Past facts","Future certainty"],a:1,f:"Se fossi ricco, viaggerei = If I were rich, I would travel. Hypothetical present/future with conditional."},
{q:"'Ne' as pronoun replaces?",o:["Direct object","Di + noun/quantity (of it/them/some)","Indirect object","Location"],a:1,f:"Ne replaces di + noun: Quanti ne vuoi? = How many of them do you want? Also: ne parlo = I speak of it."}
]
},
arabic:{
basic:[
{q:"What does 'marhaba' mean?",o:["Thank you","Goodbye","Hello","Please"],a:2,f:"Marhaba = Hello. As-salamu alaykum = Peace be upon you (formal greeting)."},
{q:"How do you say 'Thank you' in Arabic?",o:["Min fadlik","Ma'a salama","Shukran","Asif"],a:2,f:"Shukran = Thank you. Shukran jazilan = Thank you very much."},
{q:"Which direction does Arabic script run?",o:["Left to right","Top to bottom","Right to left","Bottom to top"],a:2,f:"Arabic is written right to left. Books open from the right."},
{q:"How many letters does Arabic have?",o:["22","26","28","30"],a:2,f:"Arabic has 28 letters. All consonants — short vowels are diacritical marks."},
{q:"What does 'Inshallah' mean?",o:["Thank God","If God wills / God willing","Praise God","What God wants"],a:1,f:"Inshallah = God willing. Used for any future plans. Deeply cultural expression."},
{q:"'Alhamdulillah' expresses?",o:["I'm sorry","How are you?","Praise to God / gratitude","Please"],a:2,f:"Alhamdulillah = Praise be to God. Response to 'how are you', after eating, after good news."},
{q:"What does 'ma'a' mean?",o:["Food","Bread","Water","Tea"],a:2,f:"Ma' = Water. Arabic ma' and Hindi pani both mean water!"},
{q:"What is MSA?",o:["A dialect","Modern Standard Arabic (formal written Arabic)","Egyptian Arabic","Gulf Arabic"],a:1,f:"MSA = Modern Standard Arabic. Formal, used in media/education across all 22 Arab countries."},
{q:"'Yalla' means?",o:["Goodbye","Yes","Let's go! / Come on!","Please"],a:2,f:"Yalla = Let's go! / Come on! / Hurry up! One of the most versatile informal Arabic words."},
{q:"What is a 'majlis' in Arab culture?",o:["A mosque","Traditional gathering/reception room","A market","Government office"],a:1,f:"Majlis = reception room for guests. Central to Arab hospitality (karam)."},
{q:"What does 'qahwa' mean?",o:["Tea","Juice","Coffee","Water"],a:2,f:"Qahwa = Coffee. The English word 'coffee' came from Arabic qahwa via Turkish kahve!"},
{q:"'La afham' means?",o:["I don't want","I don't know","I don't understand","I can't hear"],a:2,f:"La afham = I don't understand. La = no/not, Afham = I understand."},
{q:"Which Arab country has the Burj Khalifa?",o:["Saudi Arabia","Qatar","UAE (Dubai)","Bahrain"],a:2,f:"Burj Khalifa is in Dubai, UAE. At 828m it's the world's tallest building."},
{q:"'Ana min al-Hind' means?",o:["I live in India","I like India","I am from India","I'm going to India"],a:2,f:"Ana = I, Min = from, Al-Hind = India. Ana min al-Hind = I am from India."},
{q:"'Min fadlik' means?",o:["Excuse me","You're welcome","Thank you","Please"],a:3,f:"Min fadlik = Please (to a male). Literally 'from your grace/favour'."}
],
intermediate:[
{q:"What is the Arabic root system?",o:["No common roots","Most words derive from 3-letter roots conveying meaning families","Built from prefixes","5-letter roots only"],a:1,f:"K-T-B root: kitab=book, kitaba=writing, katib=writer, maktaba=library. Understanding roots unlocks vocabulary."},
{q:"What is the dual form?",o:["Arabic has no dual","Special form for exactly two of something","Plural form","Feminine form"],a:1,f:"Arabic has singular, dual, and plural. Dual adds -an/-ayn: kitab (1 book), kitaban (2 books)."},
{q:"What is 'idafa' in grammar?",o:["A verb type","Possessive construction (noun+noun)","Adjective agreement","A verb tense"],a:1,f:"Idafa = possessive construction. Kitab at-talib = the student's book."},
{q:"Adjective agreement in Arabic requires matching?",o:["Never change","Gender, number, and definiteness","Gender only","Number only"],a:1,f:"Adjectives agree in gender, number, and definiteness. Inanimate plurals take feminine singular adjective!"},
{q:"What is broken plural?",o:["Regular plural with suffix","Irregular plural — internal structure changes","Dual form","Feminine plural"],a:1,f:"Broken plural: kitab→kutub (books), bayt→buyut (houses). Must often be memorised."},
{q:"Fusha vs Ammiyya: what's the difference?",o:["Same thing","Fusha=formal/written, Ammiyya=regional spoken dialects","Fusha=spoken, Ammiyya=written","Age-based difference"],a:1,f:"Fusha = MSA/formal. Ammiyya = dialects (Egyptian, Gulf, Levantine) which vary by country."},
{q:"'Ma zala' expresses?",o:["No longer","Just started","Still / Continue to be","Already"],a:2,f:"Ma zala = still / continue to be. Ma zala yadrus = He is still studying."},
{q:"In which professional fields is Arabic most valuable for Indians?",o:["Agriculture","Gulf jobs, hospitality, healthcare, Islamic finance, trading","IT only","Manufacturing only"],a:1,f:"Arabic valuable for: Gulf jobs (8M Indians in GCC), Islamic finance, import/export, tourism."},
{q:"What does 'wazn' (pattern) mean in morphology?",o:["Word length","Template applied to roots to create words","A plural type","A counting system"],a:1,f:"Wazn = pattern applied to 3-letter roots. Pattern fa'ala (causative): darasa→darrasa (teach)."},
{q:"'Ala ar-raghm min' means?",o:["Because of","As a result","In spite of / Despite","In addition to"],a:2,f:"Ala ar-raghm min = in spite of / despite. Essential connector for formal Arabic."},
{q:"What are Gulf employers' language expectations?",o:["Only English","Only Arabic","Arabic + relevant professional skills","No requirement"],a:2,f:"Gulf employers expect: professional skills + functional Arabic for non-English environments."},
{q:"'Arjou an' + clause uses which mood?",o:["Indicative","Jussive","Subjunctive","Imperative"],a:2,f:"Arjou an = I hope/request that + subjunctive. Used for wishes and requests."}
],
advanced:[
{q:"What is 'tajwid' in Quranic recitation?",o:["A prayer type","Rules of proper pronunciation and recitation","A donation","A fasting type"],a:1,f:"Tajwid = rules governing correct Quran recitation. Includes pronunciation, pauses, intonation."},
{q:"'Haithu ma' means?",o:["Because","Wherever","However","Whenever"],a:1,f:"Haithu ma = wherever. Formal Arabic connector/indefinite relative particle."},
{q:"What is 'irab' (grammatical inflection)?",o:["Spelling rules","The case/mood marking system on Arabic words","Verb conjugation only","Pronunciation rules"],a:1,f:"I'rab = the system of grammatical inflection marking case (nouns) and mood (verbs) in Arabic."},
{q:"'Bal' as discourse connector means?",o:["But/Rather (correction)","And also","Therefore","Despite"],a:0,f:"Bal = but rather / on the contrary (corrective). Laysa rajulan bal imra'atan = Not a man but rather a woman."},
{q:"What are 'harakat' in Arabic script?",o:["Punctuation marks","Diacritical marks showing short vowels","Uppercase letters","Numbers"],a:1,f:"Harakat = diacritical marks: fatha (a), kasra (i), damma (u), sukun (no vowel), shadda (doubling)."},
{q:"'Fi ma yata'allaqu bi' means?",o:["According to","With regard to / As for","Despite","Because of"],a:1,f:"Fi ma yata'allaqu bi = with regard to / as for / concerning. Formal written connector."},
{q:"What is 'ism al-fa'il' (active participle)?",o:["A verb tense","A noun derived from a verb meaning the doer of the action","An adjective","A command form"],a:1,f:"Ism al-fa'il = active participle/doer noun. Katib=writer (from K-T-B=write). Mu'allim=teacher (from '-L-M=know)."},
{q:"Arabic has how many verb forms/patterns?",o:["3","5","10 (plus some rare ones)","15"],a:2,f:"Arabic has 10 main verb forms (awzan), each adding specific meaning: Form II=causative, Form V=reflexive of II, Form VIII=reflexive. Mastering forms unlocks verb comprehension."}
]
},
russian:{
basic:[
{q:"What does 'Privet' mean?",o:["Thank you","Goodbye","Hi/Hello","Please"],a:2,f:"Privet = Hi (informal). Zdravstvuyte = Hello (formal)."},
{q:"How do you say 'Thank you' in Russian?",o:["Pozhaluysta","Spasibo","Izvinite","Prostite"],a:1,f:"Spasibo = Thank you. Pozhaluysta = Please / You're welcome."},
{q:"Russian uses which script?",o:["Latin","Arabic","Cyrillic","Greek"],a:2,f:"Russian uses Cyrillic with 33 letters. Created by Saints Cyril and Methodius."},
{q:"What does 'Da' mean?",o:["No","Maybe","Goodbye","Yes"],a:3,f:"Da = Yes. Nyet = No."},
{q:"'Gde tualet?' means?",o:["Where is the hotel?","Where is the exit?","Where is the toilet?","Where is the restaurant?"],a:2,f:"Gde = Where. Tualet = Toilet."},
{q:"'Skolko stoit?' means?",o:["What time?","How much does it cost?","Where is it?","What is this?"],a:1,f:"Skolko stoit? = How much does it cost?"},
{q:"What does 'voda' mean?",o:["Food","Milk","Tea","Water"],a:3,f:"Voda = Water. Russian voda and English water share ancient Indo-European root!"},
{q:"'Ya ne ponimayu' means?",o:["I don't know","I don't want","I don't understand","I can't see"],a:2,f:"Ya ne ponimayu = I don't understand."},
{q:"'Pozhaluysta' has two meanings. What?",o:["Yes and No","Please and You're welcome","Hello and Goodbye","Thanks and Sorry"],a:1,f:"Pozhaluysta = Please AND You're welcome. One of the most versatile Russian words!"},
{q:"Russian has how many cases?",o:["3","4","6","8"],a:2,f:"6 cases: Nominative, Genitive, Dative, Accusative, Instrumental, Prepositional."},
{q:"What does 'khleb' mean?",o:["Milk","Water","Bread","Soup"],a:2,f:"Khleb = Bread. Bread-and-salt (khleb-sol) is traditional Russian hospitality."},
{q:"How do you say 'My name is Andrei'?",o:["Ya znayu Andrei","Menya zovut Andrei","Ya vizhu Andrei","Ya ischu Andrei"],a:1,f:"Menya zovut = My name is. Literally 'They call me'."},
{q:"'Dobroye utro' means?",o:["Good evening","Good night","Good morning","Goodbye"],a:2,f:"Dobroye utro = Good morning. Dobryy den = Good day. Dobryy vecher = Good evening."},
{q:"The letter P in Russian sounds like?",o:["Like English P","Rolled/trilled R","Like English R","Like English L"],a:1,f:"Russian P = trilled R! Other traps: H=N, B=V, C=S. Cyrillic looks can deceive!"},
{q:"'Ochen priyatno' is said when?",o:["Saying goodbye","Meeting someone (Nice to meet you)","Thanking someone","Ordering food"],a:1,f:"Ochen priyatno = Nice to meet you. Literally 'Very pleasant'."}
],
intermediate:[
{q:"What is the key Russian verb aspect difference?",o:["Perfective is formal","Imperfective=ongoing/habitual, Perfective=completed/single action","Perfective is past only","Interchangeable"],a:1,f:"Imperfective = ongoing/habitual. Perfective = completed/single. Every verb has an aspectual pair."},
{q:"'U menya yest' means?",o:["I am here","I go somewhere","I have (possession)","There is someone"],a:2,f:"U + genitive + yest = to have. U menya yest kniga = I have a book."},
{q:"'Ya by khotel' uses which mood?",o:["Indicative","Imperative","Conditional/Subjunctive","Future"],a:2,f:"Ya by khotel = I would like. By creates conditional mood. Polite request form."},
{q:"In genitive of negation, which case follows 'ne'?",o:["Nominative","Accusative","Genitive","Dative"],a:2,f:"After nyet and negated verbs: genitive. U menya nyet vremeni = I have no time (genitive)."},
{q:"What is the Russian patronymic?",o:["Family last name","Middle name from father's first name","Nickname","Maiden name"],a:1,f:"Otchestvo = patronymic from father's name. Ivan Petrovich = Ivan, son of Pyotr. Used in formal address."},
{q:"'Chem bolshe, tem luchshe' means?",o:["The more expensive, better","The more, the better","The older, better","The sooner, better"],a:1,f:"Chem... tem... = the... the... Chem bolshe, tem luchshe = The more, the better."},
{q:"Which case with 'v' indicates location?",o:["Accusative","Genitive","Prepositional","Dative"],a:2,f:"V + prepositional = location (where): V Moskve. V + accusative = direction (where to): V Moskvu."},
{q:"'Mne nravitsya' vs 'Ya lyublyu' difference?",o:["Same meaning","Nravitsya=I like (impression), Lyublyu=I love (deep)","Nravitsya is formal","Lyublyu is for things only"],a:1,f:"Mne nravitsya = I like (appeals to me). Ya lyublyu = I love/really like (strong feeling)."},
{q:"What does 'davay' mean informally?",o:["Give me","Let's / Come on / Okay / Bye","Why not","Please"],a:1,f:"Davay = Let's / Come on / Okay / Bye. Originally from davat (to give) but now many meanings."},
{q:"What is Matryoshka besides a toy?",o:["A soup","Nesting doll representing layered culture","A weapon","A bread type"],a:1,f:"Matryoshka = nesting doll. Symbol of Russian culture. Metaphor for anything with hidden layers."},
{q:"How express 'I've been studying for 2 years'?",o:["Past tense + 2 years","Present tense + uzhe 2 goda (already 2 years)","Future tense","Infinitive only"],a:1,f:"Russian uses present tense for ongoing actions from the past: Ya uzhe 2 goda uchus = I've been studying for 2 years."},
{q:"What is the instrumental case used for?",o:["Possession","With/by means of, predicates, passive agent","Direction","Time only"],a:1,f:"Instrumental: Ya pishu ruchkoy = I write with a pen. On stal vrachom = He became a doctor."},
{q:"'Kstati' means?",o:["First of all","However","By the way","Therefore"],a:2,f:"Kstati = By the way / Incidentally. Also means timely/relevant."},
{q:"What aspect is 'pogovorit'?",o:["Imperfective","Perfective","Both","Neither"],a:1,f:"Pogovorit = Perfective (completed conversation). Govorit = Imperfective. Po- prefix often makes perfective."}
],
advanced:[
{q:"What does perfective prefix 'po-' often add?",o:["Negation","Brief/limited duration of action","Intensity","Repetition"],a:1,f:"Po- = do briefly/for a while: porabotat = work for a bit, pochitat = read for a bit."},
{q:"'Kak by to ni bylo' means?",o:["However that may be / Be that as it may","How it was done","However you want","It doesn't matter"],a:0,f:"Kak by to ni bylo = be that as it may. Fixed idiomatic expression conceding a point."},
{q:"What is 'byvshiy'?",o:["Future","Current","Former/Ex-","Ancient"],a:2,f:"Byvshiy = former/ex-. Byvshiy prezident = former president. From byt (to be)."},
{q:"Russian verbs of motion have which unique feature?",o:["No past tense","Unidirectional vs multidirectional pairs","No future","Only one aspect"],a:1,f:"Verbs of motion come in pairs: idti (go one direction) vs khodit (go generally/repeatedly). Also: yekhat/yezdit, etc."},
{q:"What does 'nichego' mean in conversation?",o:["Something","Everything","Not bad / Okay (response to how are you)","Never"],a:2,f:"Nichego = nothing. But conversationally: Kak dela? Nichego = How are you? Not bad/okay."},
{q:"'Nesmotrya na' + accusative means?",o:["Looking at","Despite / In spite of","Because of","According to"],a:1,f:"Nesmotrya na = despite / in spite of. Nesmotrya na trudnosti = Despite the difficulties."},
{q:"What is 'razgovornyy stil' (colloquial style)?",o:["Written academic Russian","Informal spoken Russian with its own grammar patterns","Dialectal Russian","Slang only"],a:1,f:"Razgovornyy stil = informal spoken register with particle omissions, different word order, contractions. C1+ awareness."},
{q:"'V silu togo chto' means?",o:["Because / Due to the fact that","Despite","In order to","Instead of"],a:0,f:"V silu togo chto = due to the fact that / because of the fact that. Formal connector."},
{q:"What are 'chastnitsy' (particles) in Russian?",o:["Nouns","Small invariable words adding nuance (zhe, vot, ved, li, etc.)","Verbs","Adjectives"],a:1,f:"Particles add nuance: zhe=emphasis, vot=here/there, ved=after all, li=question particle. Critical for natural Russian."},
{q:"'Tem ne menee' means?",o:["More or less","Nevertheless / Nonetheless","Therefore","Meanwhile"],a:1,f:"Tem ne menee = nevertheless / nonetheless. Formal connector. Odako/vprochem are alternatives."}
]
}
};
